---

version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "8081:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: worker.Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - api

  redis:
    image: "redis:alpine"
    volumes:
      - "./redis_data/:/data"
